# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'KMP Weather Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KMP Weather Demo
pod 'MultiPlatformLibraryMvvm', :git => 'https://github.com/icerockdev/moko-mvvm.git', :tag => 'release/0.6.0'

end
